//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ReaderConfigDALProto
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ImpinjReadersConfigurationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ImpinjReadersConfigurationEntities object using the connection string found in the 'ImpinjReadersConfigurationEntities' section of the application configuration file.
        /// </summary>
        public ImpinjReadersConfigurationEntities() : base("name=ImpinjReadersConfigurationEntities", "ImpinjReadersConfigurationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ImpinjReadersConfigurationEntities object.
        /// </summary>
        public ImpinjReadersConfigurationEntities(string connectionString) : base(connectionString, "ImpinjReadersConfigurationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ImpinjReadersConfigurationEntities object.
        /// </summary>
        public ImpinjReadersConfigurationEntities(EntityConnection connection) : base(connection, "ImpinjReadersConfigurationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reader> Readers
        {
            get
            {
                if ((_Readers == null))
                {
                    _Readers = base.CreateObjectSet<Reader>("Readers");
                }
                return _Readers;
            }
        }
        private ObjectSet<Reader> _Readers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReaderAntenna> ReaderAntennas
        {
            get
            {
                if ((_ReaderAntennas == null))
                {
                    _ReaderAntennas = base.CreateObjectSet<ReaderAntenna>("ReaderAntennas");
                }
                return _ReaderAntennas;
            }
        }
        private ObjectSet<ReaderAntenna> _ReaderAntennas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Readers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReaders(Reader reader)
        {
            base.AddObject("Readers", reader);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReaderAntennas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReaderAntennas(ReaderAntenna readerAntenna)
        {
            base.AddObject("ReaderAntennas", readerAntenna);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ImpinjReadersConfigurationModel", Name="Reader")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reader : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reader object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="hostName">Initial value of the HostName property.</param>
        public static Reader CreateReader(global::System.Int64 id, global::System.String hostName)
        {
            Reader reader = new Reader();
            reader.ID = id;
            reader.HostName = hostName;
            return reader;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HostName
        {
            get
            {
                return _HostName;
            }
            set
            {
                OnHostNameChanging(value);
                ReportPropertyChanging("HostName");
                _HostName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HostName");
                OnHostNameChanged();
            }
        }
        private global::System.String _HostName;
        partial void OnHostNameChanging(global::System.String value);
        partial void OnHostNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ImpinjReadersConfigurationModel", Name="ReaderAntenna")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReaderAntenna : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReaderAntenna object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="portNumber">Initial value of the PortNumber property.</param>
        public static ReaderAntenna CreateReaderAntenna(global::System.Int64 id, global::System.Int64 portNumber)
        {
            ReaderAntenna readerAntenna = new ReaderAntenna();
            readerAntenna.ID = id;
            readerAntenna.PortNumber = portNumber;
            return readerAntenna;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PortNumber
        {
            get
            {
                return _PortNumber;
            }
            set
            {
                OnPortNumberChanging(value);
                ReportPropertyChanging("PortNumber");
                _PortNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortNumber");
                OnPortNumberChanged();
            }
        }
        private global::System.Int64 _PortNumber;
        partial void OnPortNumberChanging(global::System.Int64 value);
        partial void OnPortNumberChanged();

        #endregion
    
    }

    #endregion
    
}
