//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ImpinjReadersConfigurationModel", "FK_ReaderAntenna_0_0", "Reader", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(OmniRevolutionRFIDService.Reader), "ReaderAntenna", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OmniRevolutionRFIDService.ReaderAntenna), true)]

#endregion

namespace OmniRevolutionRFIDService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ImpinjReadersConfigurationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ImpinjReadersConfigurationEntities object using the connection string found in the 'ImpinjReadersConfigurationEntities' section of the application configuration file.
        /// </summary>
        public ImpinjReadersConfigurationEntities() : base("name=ImpinjReadersConfigurationEntities", "ImpinjReadersConfigurationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ImpinjReadersConfigurationEntities object.
        /// </summary>
        public ImpinjReadersConfigurationEntities(string connectionString) : base(connectionString, "ImpinjReadersConfigurationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ImpinjReadersConfigurationEntities object.
        /// </summary>
        public ImpinjReadersConfigurationEntities(EntityConnection connection) : base(connection, "ImpinjReadersConfigurationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reader> Readers
        {
            get
            {
                if ((_Readers == null))
                {
                    _Readers = base.CreateObjectSet<Reader>("Readers");
                }
                return _Readers;
            }
        }
        private ObjectSet<Reader> _Readers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReaderAntenna> ReaderAntennas
        {
            get
            {
                if ((_ReaderAntennas == null))
                {
                    _ReaderAntennas = base.CreateObjectSet<ReaderAntenna>("ReaderAntennas");
                }
                return _ReaderAntennas;
            }
        }
        private ObjectSet<ReaderAntenna> _ReaderAntennas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Readers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReaders(Reader reader)
        {
            base.AddObject("Readers", reader);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReaderAntennas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReaderAntennas(ReaderAntenna readerAntenna)
        {
            base.AddObject("ReaderAntennas", readerAntenna);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ImpinjReadersConfigurationModel", Name="Reader")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reader : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reader object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="hostName">Initial value of the HostName property.</param>
        public static Reader CreateReader(global::System.Int64 id, global::System.String hostName)
        {
            Reader reader = new Reader();
            reader.ID = id;
            reader.HostName = hostName;
            return reader;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HostName
        {
            get
            {
                return _HostName;
            }
            set
            {
                OnHostNameChanging(value);
                ReportPropertyChanging("HostName");
                _HostName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HostName");
                OnHostNameChanged();
            }
        }
        private global::System.String _HostName;
        partial void OnHostNameChanging(global::System.String value);
        partial void OnHostNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrentStatus
        {
            get
            {
                return _CurrentStatus;
            }
            set
            {
                OnCurrentStatusChanging(value);
                ReportPropertyChanging("CurrentStatus");
                _CurrentStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CurrentStatus");
                OnCurrentStatusChanged();
            }
        }
        private global::System.String _CurrentStatus;
        partial void OnCurrentStatusChanging(global::System.String value);
        partial void OnCurrentStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastPing
        {
            get
            {
                return _LastPing;
            }
            set
            {
                OnLastPingChanging(value);
                ReportPropertyChanging("LastPing");
                _LastPing = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastPing");
                OnLastPingChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastPing;
        partial void OnLastPingChanging(Nullable<global::System.DateTime> value);
        partial void OnLastPingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReaderID
        {
            get
            {
                return _ReaderID;
            }
            set
            {
                OnReaderIDChanging(value);
                ReportPropertyChanging("ReaderID");
                _ReaderID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReaderID");
                OnReaderIDChanged();
            }
        }
        private global::System.String _ReaderID;
        partial void OnReaderIDChanging(global::System.String value);
        partial void OnReaderIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ImpinjReadersConfigurationModel", "FK_ReaderAntenna_0_0", "ReaderAntenna")]
        public EntityCollection<ReaderAntenna> ReaderAntennas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReaderAntenna>("ImpinjReadersConfigurationModel.FK_ReaderAntenna_0_0", "ReaderAntenna");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReaderAntenna>("ImpinjReadersConfigurationModel.FK_ReaderAntenna_0_0", "ReaderAntenna", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ImpinjReadersConfigurationModel", Name="ReaderAntenna")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReaderAntenna : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReaderAntenna object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="portNumber">Initial value of the PortNumber property.</param>
        public static ReaderAntenna CreateReaderAntenna(global::System.Int64 id, global::System.Int64 portNumber)
        {
            ReaderAntenna readerAntenna = new ReaderAntenna();
            readerAntenna.ID = id;
            readerAntenna.PortNumber = portNumber;
            return readerAntenna;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FK_ID_Reader
        {
            get
            {
                return _FK_ID_Reader;
            }
            set
            {
                OnFK_ID_ReaderChanging(value);
                ReportPropertyChanging("FK_ID_Reader");
                _FK_ID_Reader = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_ID_Reader");
                OnFK_ID_ReaderChanged();
            }
        }
        private Nullable<global::System.Int64> _FK_ID_Reader;
        partial void OnFK_ID_ReaderChanging(Nullable<global::System.Int64> value);
        partial void OnFK_ID_ReaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PortNumber
        {
            get
            {
                return _PortNumber;
            }
            set
            {
                OnPortNumberChanging(value);
                ReportPropertyChanging("PortNumber");
                _PortNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortNumber");
                OnPortNumberChanged();
            }
        }
        private global::System.Int64 _PortNumber;
        partial void OnPortNumberChanging(global::System.Int64 value);
        partial void OnPortNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ImpinjReadersConfigurationModel", "FK_ReaderAntenna_0_0", "Reader")]
        public Reader Reader
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("ImpinjReadersConfigurationModel.FK_ReaderAntenna_0_0", "Reader").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("ImpinjReadersConfigurationModel.FK_ReaderAntenna_0_0", "Reader").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reader> ReaderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("ImpinjReadersConfigurationModel.FK_ReaderAntenna_0_0", "Reader");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reader>("ImpinjReadersConfigurationModel.FK_ReaderAntenna_0_0", "Reader", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
