//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ConfigDatabaseModel", "FK_ConfigItem_0_0", "ConfigItemType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConfigDatabaseDAL.ConfigItemType), "ConfigItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConfigDatabaseDAL.ConfigItem))]
[assembly: EdmRelationshipAttribute("ConfigDatabaseModel", "FK_ConfigItem_1_0", "ConfigItemGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConfigDatabaseDAL.ConfigItemGroup), "ConfigItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConfigDatabaseDAL.ConfigItem))]

#endregion

namespace ConfigDatabaseDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ConfigDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConfigDatabaseEntities object using the connection string found in the 'ConfigDatabaseEntities' section of the application configuration file.
        /// </summary>
        public ConfigDatabaseEntities() : base("name=ConfigDatabaseEntities", "ConfigDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConfigDatabaseEntities object.
        /// </summary>
        public ConfigDatabaseEntities(string connectionString) : base(connectionString, "ConfigDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConfigDatabaseEntities object.
        /// </summary>
        public ConfigDatabaseEntities(EntityConnection connection) : base(connection, "ConfigDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConfigItem> ConfigItem
        {
            get
            {
                if ((_ConfigItem == null))
                {
                    _ConfigItem = base.CreateObjectSet<ConfigItem>("ConfigItem");
                }
                return _ConfigItem;
            }
        }
        private ObjectSet<ConfigItem> _ConfigItem;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConfigItemGroup> ConfigItemGroup
        {
            get
            {
                if ((_ConfigItemGroup == null))
                {
                    _ConfigItemGroup = base.CreateObjectSet<ConfigItemGroup>("ConfigItemGroup");
                }
                return _ConfigItemGroup;
            }
        }
        private ObjectSet<ConfigItemGroup> _ConfigItemGroup;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConfigItemType> ConfigItemType
        {
            get
            {
                if ((_ConfigItemType == null))
                {
                    _ConfigItemType = base.CreateObjectSet<ConfigItemType>("ConfigItemType");
                }
                return _ConfigItemType;
            }
        }
        private ObjectSet<ConfigItemType> _ConfigItemType;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfigItem EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigItem(ConfigItem configItem)
        {
            base.AddObject("ConfigItem", configItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfigItemGroup EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigItemGroup(ConfigItemGroup configItemGroup)
        {
            base.AddObject("ConfigItemGroup", configItemGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfigItemType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigItemType(ConfigItemType configItemType)
        {
            base.AddObject("ConfigItemType", configItemType);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConfigDatabaseModel", Name="ConfigItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConfigItem object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ConfigItem CreateConfigItem(global::System.Int64 id, global::System.String name)
        {
            ConfigItem configItem = new ConfigItem();
            configItem.ID = id;
            configItem.Name = name;
            return configItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConfigDatabaseModel", "FK_ConfigItem_0_0", "ConfigItemType")]
        public ConfigItemType ConfigItemType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemType>("ConfigDatabaseModel.FK_ConfigItem_0_0", "ConfigItemType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemType>("ConfigDatabaseModel.FK_ConfigItem_0_0", "ConfigItemType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ConfigItemType> ConfigItemTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemType>("ConfigDatabaseModel.FK_ConfigItem_0_0", "ConfigItemType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ConfigItemType>("ConfigDatabaseModel.FK_ConfigItem_0_0", "ConfigItemType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConfigDatabaseModel", "FK_ConfigItem_1_0", "ConfigItemGroup")]
        public ConfigItemGroup ConfigItemGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemGroup>("ConfigDatabaseModel.FK_ConfigItem_1_0", "ConfigItemGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemGroup>("ConfigDatabaseModel.FK_ConfigItem_1_0", "ConfigItemGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ConfigItemGroup> ConfigItemGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemGroup>("ConfigDatabaseModel.FK_ConfigItem_1_0", "ConfigItemGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ConfigItemGroup>("ConfigDatabaseModel.FK_ConfigItem_1_0", "ConfigItemGroup", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConfigDatabaseModel", Name="ConfigItemGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigItemGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConfigItemGroup object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ConfigItemGroup CreateConfigItemGroup(global::System.Int64 id, global::System.String name)
        {
            ConfigItemGroup configItemGroup = new ConfigItemGroup();
            configItemGroup.ID = id;
            configItemGroup.Name = name;
            return configItemGroup;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConfigDatabaseModel", "FK_ConfigItem_1_0", "ConfigItem")]
        public EntityCollection<ConfigItem> ConfigItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConfigItem>("ConfigDatabaseModel.FK_ConfigItem_1_0", "ConfigItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConfigItem>("ConfigDatabaseModel.FK_ConfigItem_1_0", "ConfigItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConfigDatabaseModel", Name="ConfigItemType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigItemType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConfigItemType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ConfigItemType CreateConfigItemType(global::System.Int64 id, global::System.String name)
        {
            ConfigItemType configItemType = new ConfigItemType();
            configItemType.ID = id;
            configItemType.Name = name;
            return configItemType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegEx
        {
            get
            {
                return _RegEx;
            }
            set
            {
                OnRegExChanging(value);
                ReportPropertyChanging("RegEx");
                _RegEx = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegEx");
                OnRegExChanged();
            }
        }
        private global::System.String _RegEx;
        partial void OnRegExChanging(global::System.String value);
        partial void OnRegExChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ConfigDatabaseModel", "FK_ConfigItem_0_0", "ConfigItem")]
        public EntityCollection<ConfigItem> ConfigItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConfigItem>("ConfigDatabaseModel.FK_ConfigItem_0_0", "ConfigItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConfigItem>("ConfigDatabaseModel.FK_ConfigItem_0_0", "ConfigItem", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
