//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgestoneSimulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6c")]
        public string WorkstationName {
            get {
                return ((string)(this["WorkstationName"]));
            }
            set {
                this["WorkstationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>6c,a94b8ce0-a6d9-4eb3-8b7c-bce4b6dc4a62,0</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StationTable {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StationTable"]));
            }
            set {
                this["StationTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>222911100D22040314000176,0D22040314000176</string>
  <string>222931100D22040314000212,0D22040314000212</string>
  <string>222931100D22040314000219,0D22040314000219</string>
  <string>222931100D22040314000206,0D22040314000206</string>
  <string>222911100D22040314000175,0D22040314000175</string>
  <string>222931100D22040314000230,0D22040314000230</string>
  <string>222931100D22040314000210,0D22040314000210</string>
  <string>222911100D22040314000152,0D22040314000152</string>
  <string>222911100D22040314000153,0D22040314000153</string>
  <string>222911100D22040314000154,0D22040314000154</string>
  <string>222911100D22040314000155,0D22040314000155</string>
  <string>222911100D22040314000156,0D22040314000156</string>
  <string>222931100D22040314000589,0D22040314000589</string>
  <string>222911100D22040314000173,0D22040314000173</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RackTable {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RackTable"]));
            }
            set {
                this["RackTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:3000")]
        public string CALCManAddress {
            get {
                return ((string)(this["CALCManAddress"]));
            }
            set {
                this["CALCManAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:30525")]
        public string ImageGenAddress {
            get {
                return ((string)(this["ImageGenAddress"]));
            }
            set {
                this["ImageGenAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:4000")]
        public string RFIDReaderAddress {
            get {
                return ((string)(this["RFIDReaderAddress"]));
            }
            set {
                this["RFIDReaderAddress"] = value;
            }
        }
    }
}
