//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGenModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTypeDynamicAttributeValue
    {
        public int ID { get; set; }
        public int FK_ID_AssetTypeDynamicAttribute { get; set; }
        public string Value { get; set; }
        public Nullable<int> FK_ID_Asset { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte[] Version { get; set; }
        public int EditState { get; set; }
    
        public virtual AssetTypeDynamicAttribute AssetTypeDynamicAttribute { get; set; }
    }
}
