//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGenModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTypeDynamicAttribute
    {
        public AssetTypeDynamicAttribute()
        {
            this.AssetTypeDynamicAttributeValues = new HashSet<AssetTypeDynamicAttributeValue>();
        }
    
        public int ID { get; set; }
        public int FK_ID_AssetType { get; set; }
        public int FK_ID_DynamicAttributeType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DefaultValue { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsNullable { get; set; }
        public byte[] Version { get; set; }
        public int EditState { get; set; }
    
        public virtual ICollection<AssetTypeDynamicAttributeValue> AssetTypeDynamicAttributeValues { get; set; }
    }
}
