//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGenModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelTemplateType
    {
        public LabelTemplateType()
        {
            this.LabelTemplates = new HashSet<LabelTemplate>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<LabelTemplate> LabelTemplates { get; set; }
    }
}
