//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGenModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelTemplate
    {
        public int ID { get; set; }
        public string TemplateName { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string TemplateFileName { get; set; }
        public Nullable<int> FK_ID_ConnectedDevices { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public int EditState { get; set; }
        public byte[] Version { get; set; }
        public byte[] BTWBinary { get; set; }
        public Nullable<int> FK_ID_LabelTemplateType { get; set; }
        public string ProviewXML { get; set; }
    
        public virtual LabelTemplateType LabelTemplateType { get; set; }
    }
}
