//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RFIDServiceConfigModel", "FK_Antenna_0_0", "Reader", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RFIDServiceConfig.Web.Models.Reader), "Antenna", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RFIDServiceConfig.Web.Models.Antenna), true)]
[assembly: EdmRelationshipAttribute("RFIDServiceConfigModel", "FK_ConfigItem_0_0", "Reader", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RFIDServiceConfig.Web.Models.Reader), "ConfigItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RFIDServiceConfig.Web.Models.ConfigItem), true)]
[assembly: EdmRelationshipAttribute("RFIDServiceConfigModel", "FK_ConfigItem_1_0", "ConfigItemType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RFIDServiceConfig.Web.Models.ConfigItemType), "ConfigItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RFIDServiceConfig.Web.Models.ConfigItem), true)]
[assembly: EdmRelationshipAttribute("RFIDServiceConfigModel", "FK_ConfigItem_2_0", "ConfigItemGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RFIDServiceConfig.Web.Models.ConfigItemGroup), "ConfigItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RFIDServiceConfig.Web.Models.ConfigItem), true)]

#endregion

namespace RFIDServiceConfig.Web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RFIDServiceConfigEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RFIDServiceConfigEntities object using the connection string found in the 'RFIDServiceConfigEntities' section of the application configuration file.
        /// </summary>
        public RFIDServiceConfigEntities() : base("name=RFIDServiceConfigEntities", "RFIDServiceConfigEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RFIDServiceConfigEntities object.
        /// </summary>
        public RFIDServiceConfigEntities(string connectionString) : base(connectionString, "RFIDServiceConfigEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RFIDServiceConfigEntities object.
        /// </summary>
        public RFIDServiceConfigEntities(EntityConnection connection) : base(connection, "RFIDServiceConfigEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Antenna> Antennae
        {
            get
            {
                if ((_Antennae == null))
                {
                    _Antennae = base.CreateObjectSet<Antenna>("Antennae");
                }
                return _Antennae;
            }
        }
        private ObjectSet<Antenna> _Antennae;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConfigItem> ConfigItems
        {
            get
            {
                if ((_ConfigItems == null))
                {
                    _ConfigItems = base.CreateObjectSet<ConfigItem>("ConfigItems");
                }
                return _ConfigItems;
            }
        }
        private ObjectSet<ConfigItem> _ConfigItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConfigItemGroup> ConfigItemGroups
        {
            get
            {
                if ((_ConfigItemGroups == null))
                {
                    _ConfigItemGroups = base.CreateObjectSet<ConfigItemGroup>("ConfigItemGroups");
                }
                return _ConfigItemGroups;
            }
        }
        private ObjectSet<ConfigItemGroup> _ConfigItemGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConfigItemType> ConfigItemTypes
        {
            get
            {
                if ((_ConfigItemTypes == null))
                {
                    _ConfigItemTypes = base.CreateObjectSet<ConfigItemType>("ConfigItemTypes");
                }
                return _ConfigItemTypes;
            }
        }
        private ObjectSet<ConfigItemType> _ConfigItemTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reader> Readers
        {
            get
            {
                if ((_Readers == null))
                {
                    _Readers = base.CreateObjectSet<Reader>("Readers");
                }
                return _Readers;
            }
        }
        private ObjectSet<Reader> _Readers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Antennae EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAntennae(Antenna antenna)
        {
            base.AddObject("Antennae", antenna);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfigItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigItems(ConfigItem configItem)
        {
            base.AddObject("ConfigItems", configItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfigItemGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigItemGroups(ConfigItemGroup configItemGroup)
        {
            base.AddObject("ConfigItemGroups", configItemGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfigItemTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigItemTypes(ConfigItemType configItemType)
        {
            base.AddObject("ConfigItemTypes", configItemType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Readers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReaders(Reader reader)
        {
            base.AddObject("Readers", reader);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RFIDServiceConfigModel", Name="Antenna")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Antenna : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Antenna object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="port">Initial value of the Port property.</param>
        /// <param name="txPowerIndBm">Initial value of the TxPowerIndBm property.</param>
        /// <param name="fK_ID_Reader">Initial value of the FK_ID_Reader property.</param>
        public static Antenna CreateAntenna(global::System.Int64 id, global::System.Int64 port, global::System.Int64 txPowerIndBm, global::System.Int64 fK_ID_Reader)
        {
            Antenna antenna = new Antenna();
            antenna.ID = id;
            antenna.Port = port;
            antenna.TxPowerIndBm = txPowerIndBm;
            antenna.FK_ID_Reader = fK_ID_Reader;
            return antenna;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private global::System.Int64 _Port;
        partial void OnPortChanging(global::System.Int64 value);
        partial void OnPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TxPowerIndBm
        {
            get
            {
                return _TxPowerIndBm;
            }
            set
            {
                OnTxPowerIndBmChanging(value);
                ReportPropertyChanging("TxPowerIndBm");
                _TxPowerIndBm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TxPowerIndBm");
                OnTxPowerIndBmChanged();
            }
        }
        private global::System.Int64 _TxPowerIndBm;
        partial void OnTxPowerIndBmChanging(global::System.Int64 value);
        partial void OnTxPowerIndBmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_ID_Reader
        {
            get
            {
                return _FK_ID_Reader;
            }
            set
            {
                OnFK_ID_ReaderChanging(value);
                ReportPropertyChanging("FK_ID_Reader");
                _FK_ID_Reader = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_ID_Reader");
                OnFK_ID_ReaderChanged();
            }
        }
        private global::System.Int64 _FK_ID_Reader;
        partial void OnFK_ID_ReaderChanging(global::System.Int64 value);
        partial void OnFK_ID_ReaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDefault
        {
            get
            {
                return _IsDefault;
            }
            set
            {
                OnIsDefaultChanging(value);
                ReportPropertyChanging("IsDefault");
                _IsDefault = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDefault");
                OnIsDefaultChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDefault;
        partial void OnIsDefaultChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDefaultChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RFIDServiceConfigModel", "FK_Antenna_0_0", "Reader")]
        public Reader Reader
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("RFIDServiceConfigModel.FK_Antenna_0_0", "Reader").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("RFIDServiceConfigModel.FK_Antenna_0_0", "Reader").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reader> ReaderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("RFIDServiceConfigModel.FK_Antenna_0_0", "Reader");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reader>("RFIDServiceConfigModel.FK_Antenna_0_0", "Reader", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RFIDServiceConfigModel", Name="ConfigItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConfigItem object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="fK_ID_CONFIG_ITEM_GROUP">Initial value of the FK_ID_CONFIG_ITEM_GROUP property.</param>
        /// <param name="fK_ID_CONFIG_ITEM_TYPE">Initial value of the FK_ID_CONFIG_ITEM_TYPE property.</param>
        /// <param name="fK_ID_Reader">Initial value of the FK_ID_Reader property.</param>
        public static ConfigItem CreateConfigItem(global::System.Int64 id, global::System.String name, global::System.Int64 fK_ID_CONFIG_ITEM_GROUP, global::System.Int64 fK_ID_CONFIG_ITEM_TYPE, global::System.Int64 fK_ID_Reader)
        {
            ConfigItem configItem = new ConfigItem();
            configItem.ID = id;
            configItem.Name = name;
            configItem.FK_ID_CONFIG_ITEM_GROUP = fK_ID_CONFIG_ITEM_GROUP;
            configItem.FK_ID_CONFIG_ITEM_TYPE = fK_ID_CONFIG_ITEM_TYPE;
            configItem.FK_ID_Reader = fK_ID_Reader;
            return configItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_ID_CONFIG_ITEM_GROUP
        {
            get
            {
                return _FK_ID_CONFIG_ITEM_GROUP;
            }
            set
            {
                OnFK_ID_CONFIG_ITEM_GROUPChanging(value);
                ReportPropertyChanging("FK_ID_CONFIG_ITEM_GROUP");
                _FK_ID_CONFIG_ITEM_GROUP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_ID_CONFIG_ITEM_GROUP");
                OnFK_ID_CONFIG_ITEM_GROUPChanged();
            }
        }
        private global::System.Int64 _FK_ID_CONFIG_ITEM_GROUP;
        partial void OnFK_ID_CONFIG_ITEM_GROUPChanging(global::System.Int64 value);
        partial void OnFK_ID_CONFIG_ITEM_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_ID_CONFIG_ITEM_TYPE
        {
            get
            {
                return _FK_ID_CONFIG_ITEM_TYPE;
            }
            set
            {
                OnFK_ID_CONFIG_ITEM_TYPEChanging(value);
                ReportPropertyChanging("FK_ID_CONFIG_ITEM_TYPE");
                _FK_ID_CONFIG_ITEM_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_ID_CONFIG_ITEM_TYPE");
                OnFK_ID_CONFIG_ITEM_TYPEChanged();
            }
        }
        private global::System.Int64 _FK_ID_CONFIG_ITEM_TYPE;
        partial void OnFK_ID_CONFIG_ITEM_TYPEChanging(global::System.Int64 value);
        partial void OnFK_ID_CONFIG_ITEM_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FK_ID_Reader
        {
            get
            {
                return _FK_ID_Reader;
            }
            set
            {
                OnFK_ID_ReaderChanging(value);
                ReportPropertyChanging("FK_ID_Reader");
                _FK_ID_Reader = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_ID_Reader");
                OnFK_ID_ReaderChanged();
            }
        }
        private global::System.Int64 _FK_ID_Reader;
        partial void OnFK_ID_ReaderChanging(global::System.Int64 value);
        partial void OnFK_ID_ReaderChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RFIDServiceConfigModel", "FK_ConfigItem_0_0", "Reader")]
        public Reader Reader
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("RFIDServiceConfigModel.FK_ConfigItem_0_0", "Reader").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("RFIDServiceConfigModel.FK_ConfigItem_0_0", "Reader").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reader> ReaderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reader>("RFIDServiceConfigModel.FK_ConfigItem_0_0", "Reader");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reader>("RFIDServiceConfigModel.FK_ConfigItem_0_0", "Reader", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RFIDServiceConfigModel", "FK_ConfigItem_1_0", "ConfigItemType")]
        public ConfigItemType ConfigItemType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemType>("RFIDServiceConfigModel.FK_ConfigItem_1_0", "ConfigItemType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemType>("RFIDServiceConfigModel.FK_ConfigItem_1_0", "ConfigItemType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ConfigItemType> ConfigItemTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemType>("RFIDServiceConfigModel.FK_ConfigItem_1_0", "ConfigItemType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ConfigItemType>("RFIDServiceConfigModel.FK_ConfigItem_1_0", "ConfigItemType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RFIDServiceConfigModel", "FK_ConfigItem_2_0", "ConfigItemGroup")]
        public ConfigItemGroup ConfigItemGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemGroup>("RFIDServiceConfigModel.FK_ConfigItem_2_0", "ConfigItemGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemGroup>("RFIDServiceConfigModel.FK_ConfigItem_2_0", "ConfigItemGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ConfigItemGroup> ConfigItemGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConfigItemGroup>("RFIDServiceConfigModel.FK_ConfigItem_2_0", "ConfigItemGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ConfigItemGroup>("RFIDServiceConfigModel.FK_ConfigItem_2_0", "ConfigItemGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RFIDServiceConfigModel", Name="ConfigItemGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigItemGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConfigItemGroup object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ConfigItemGroup CreateConfigItemGroup(global::System.Int64 id, global::System.String name)
        {
            ConfigItemGroup configItemGroup = new ConfigItemGroup();
            configItemGroup.ID = id;
            configItemGroup.Name = name;
            return configItemGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RFIDServiceConfigModel", "FK_ConfigItem_2_0", "ConfigItem")]
        public EntityCollection<ConfigItem> ConfigItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConfigItem>("RFIDServiceConfigModel.FK_ConfigItem_2_0", "ConfigItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConfigItem>("RFIDServiceConfigModel.FK_ConfigItem_2_0", "ConfigItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RFIDServiceConfigModel", Name="ConfigItemType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigItemType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConfigItemType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ConfigItemType CreateConfigItemType(global::System.Int64 id, global::System.String name)
        {
            ConfigItemType configItemType = new ConfigItemType();
            configItemType.ID = id;
            configItemType.Name = name;
            return configItemType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegEx
        {
            get
            {
                return _RegEx;
            }
            set
            {
                OnRegExChanging(value);
                ReportPropertyChanging("RegEx");
                _RegEx = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegEx");
                OnRegExChanged();
            }
        }
        private global::System.String _RegEx;
        partial void OnRegExChanging(global::System.String value);
        partial void OnRegExChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RFIDServiceConfigModel", "FK_ConfigItem_1_0", "ConfigItem")]
        public EntityCollection<ConfigItem> ConfigItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConfigItem>("RFIDServiceConfigModel.FK_ConfigItem_1_0", "ConfigItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConfigItem>("RFIDServiceConfigModel.FK_ConfigItem_1_0", "ConfigItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RFIDServiceConfigModel", Name="Reader")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reader : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reader object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="hostName">Initial value of the HostName property.</param>
        public static Reader CreateReader(global::System.Int64 id, global::System.String hostName)
        {
            Reader reader = new Reader();
            reader.ID = id;
            reader.HostName = hostName;
            return reader;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HostName
        {
            get
            {
                return _HostName;
            }
            set
            {
                OnHostNameChanging(value);
                ReportPropertyChanging("HostName");
                _HostName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HostName");
                OnHostNameChanged();
            }
        }
        private global::System.String _HostName;
        partial void OnHostNameChanging(global::System.String value);
        partial void OnHostNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrentStatus
        {
            get
            {
                return _CurrentStatus;
            }
            set
            {
                OnCurrentStatusChanging(value);
                ReportPropertyChanging("CurrentStatus");
                _CurrentStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CurrentStatus");
                OnCurrentStatusChanged();
            }
        }
        private global::System.String _CurrentStatus;
        partial void OnCurrentStatusChanging(global::System.String value);
        partial void OnCurrentStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastPing
        {
            get
            {
                return _LastPing;
            }
            set
            {
                OnLastPingChanging(value);
                ReportPropertyChanging("LastPing");
                _LastPing = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastPing");
                OnLastPingChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastPing;
        partial void OnLastPingChanging(Nullable<global::System.DateTime> value);
        partial void OnLastPingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReaderID
        {
            get
            {
                return _ReaderID;
            }
            set
            {
                OnReaderIDChanging(value);
                ReportPropertyChanging("ReaderID");
                _ReaderID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReaderID");
                OnReaderIDChanged();
            }
        }
        private global::System.String _ReaderID;
        partial void OnReaderIDChanging(global::System.String value);
        partial void OnReaderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDefault
        {
            get
            {
                return _IsDefault;
            }
            set
            {
                OnIsDefaultChanging(value);
                ReportPropertyChanging("IsDefault");
                _IsDefault = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDefault");
                OnIsDefaultChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDefault;
        partial void OnIsDefaultChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDefaultChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RFIDServiceConfigModel", "FK_Antenna_0_0", "Antenna")]
        public EntityCollection<Antenna> Antennae
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Antenna>("RFIDServiceConfigModel.FK_Antenna_0_0", "Antenna");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Antenna>("RFIDServiceConfigModel.FK_Antenna_0_0", "Antenna", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RFIDServiceConfigModel", "FK_ConfigItem_0_0", "ConfigItem")]
        public EntityCollection<ConfigItem> ConfigItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConfigItem>("RFIDServiceConfigModel.FK_ConfigItem_0_0", "ConfigItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConfigItem>("RFIDServiceConfigModel.FK_ConfigItem_0_0", "ConfigItem", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
